export const game = {
    gameTick: 0,
    gameStarted: false,
    gamePaused: true,
    gameOver: false,
    gameSpeed: 1000,

    population: 10,
    sheltered: 0,
    educated: 0,
    educatedLimit: 0,
    childrens: 0,
    fertilityRate: 20,
    
    resourceLimit: 0,
    
    //Professions
    idle: 10,
    worker: 0,
    farmer: 0,
    herdsman: 0,
    lumberjack: 0,
    tailor_prof: 0,
    teacher: 0,
    blacksmith_prof: 0,
    miner: 0,

    worker_jobs: 0,
    farmer_jobs: 0,
    herdsman_jobs: 0,
    lumberjack_jobs: 0,
    tailor_jobs: 0,
    teacher_jobs: 0,
    blacksmith_jobs: 0,
    miner_jobs: 0,

    //Resources
    food: 50,
    crop: 0,
    leather: 0,
    wood: 20,
    firewood: 20,
    stone: 10,
    iron: 0,
    clothes: 50,
    tools: 50,
    
    food_balance: 0,
    crop_balance: 0,
    leather_balance: 0,
    wood_balance: 0,
    firewood_balance: 0,
    stone_balance: 0,
    iron_balance: 0,
    clothes_balance: 0,
    tools_balance: 0,
    
    food_lack: false,
    crop_lack: false,
    leather_lack: false,
    wood_lack: false,
    firewood_lack: false,
    stone_lack: false,
    iron_lack: false,
    clothes_lack: false,
    tools_lack: false,
    
    productivity: 0,
    happiness: 1,
    health: 1,
    
    house: 0,
    school: 0,
    cropField: 0,
    farm: 0,
    tailor: 0,
    blacksmith: 0,
    lumbermill: 0,
    sawmill: 0,
    warehouse: 0,
    quarry: 0,
    mine: 0,
    
    warehouseStorage: 50,
    
    hungry: 0,
    
    totalDays: 0,
    score: 0,
    popRecord: 0,
    
    season: "spring",
    day: 0,
    weather: "sun",
}