export const game = {
    villageName: "",
    gameTick: 0,
    gameStarted: false,
    gamePaused: true,
    gameOver: false,
    gameSurrender: false,
    gameSpeed: 1000,
    gameDifficulty: "normal",
    seasonLength: 30,

    population: 10,
    sheltered: 0,
    childrens: 0,
    fertilityRate: 20,
    
    science: 0,
    resourceLimit: 0,
    
    //Professions
    idle: 10,
    worker: 0,
    farmer: 0,
    lumberjack: 0,
    tailor_prof: 0,
    brewer: 0,
    academic: 0,
    blacksmith_prof: 0,
    miner: 0,

    worker_jobs: 0,
    farmer_jobs: 0,
    lumberjack_jobs: 0,
    tailor_jobs: 0,
    brewer_jobs: 0,
    academic_jobs: 0,
    blacksmith_jobs: 0,
    miner_jobs: 0,

    //Resources
    grain: 50,
    fruit: 25,
    meat: 20,
    crop: 0,
    leather: 0,
    wood: 20,
    firewood: 20,
    stone: 10,
    iron: 0,
    clothes: 50,
    tools: 50,
    ale: 10,
    
    grain_balance: 0,
    fruit_balance: 0,
    meat_balance: 0,
    leather_balance: 0,
    wood_balance: 0,
    firewood_balance: 0,
    stone_balance: 0,
    iron_balance: 0,
    clothes_balance: 0,
    tools_balance: 0,
    ale_balance: 0,
    
    grain_lack: false,
    fruit_lack: false,
    meat_lack: false,
    leather_lack: false,
    wood_lack: false,
    firewood_lack: false,
    stone_lack: false,
    iron_lack: false,
    clothes_lack: false,
    tools_lack: false,
    ale_lack: false,
    
    productivity: 0,
    happiness: 0.5,
    health: 1,
    
    house: 0,
    stoneHouse: 0,
    school: 0,
    cropField: 0,
    farm: 0,
    tailor: 0,
    blacksmith: 0,
    lumbermill: 0,
    sawmill: 0,
    warehouse: 0,
    quarry: 0,
    mine: 0,
    tavern: 0,
    
    warehouseStorage: 50,
    
    hungry: 0,
    
    totalDays: 0,
    score: 0,
    popRecord: 0,
    
    season: "spring",
    day: 0,
    weather: "sun",
}